#version 450
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
layout(rgba32f,set = 0, binding = 0) uniform image2D BRDF;
#include "math.glsl"

vec2 Intergrate(float NdotV, float roughness)
{
    vec3 v;
    v.x = sqrt(1.0 - NdotV * NdotV);
    v.y = 0.0;
    v.z = NdotV;

    float A = 0.0;
    float B = 0.0;

    vec3 N = vec3(0.0, 0.0, 1.0);

    const int SAMPLE_COUNT = 1024;

    for (int i = 0; i < SAMPLE_COUNT; ++i)
    {
        vec2 Xi = Hammersley(i, SAMPLE_COUNT);
        vec3 H = ImportanceSampleGGX(Xi, N, roughness);
        vec3 L = normalize(2.0 * dot(v, H) * H - v);

        float NdotL = max(L.z, 0.0);
        float NdotH = max(H.z, 0.0);
        float VdotH = max(dot(v, H), 0.0);

        if (NdotL > 0.0)
        {
            float G = GeometrySmith(N, v, L, roughness);
            float G_Vis = (G * VdotH) / (NdotH * NdotV);
            float Fc = pow(1.0 - VdotH, 5.0);

            A += (1.0 - Fc) * G_Vis;
            B += Fc * G_Vis;
        }
    }

    A /= float(SAMPLE_COUNT);
    B /= float(SAMPLE_COUNT);

    return vec2(A, B);
}
void main()
{
    vec2 uv = (gl_GlobalInvocationID.xy + 0.5) / imageSize(BRDF).xy;
    vec2 intergratedBDRF = Intergrate(uv.x , uv.y);
    imageStore(BRDF, ivec2(gl_GlobalInvocationID.xy), vec4(intergratedBDRF, 0.0, 1.0));
}