#version 450
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
layout(set = 0, binding = 0) uniform sampler2D environmentMap;
layout(rgba32f,set = 0, binding = 1) uniform imageCube irradianceImage;

const float PI = 3.14159265;

const vec2 invATan = vec2(0.1591, 0.3183);
vec2 SampleSphericalMap(vec3 v)
{
    vec2 uv = vec2(atan(v.z, v.x), asin(v.y));
    uv *= invATan;
    uv += 0.5;
    return uv;
}

vec3 GetNormal(uint face, vec2 uv)
{
    uv = uv * 2.0 - 1.0;

    switch (face)
    {
        case 0: return normalize(vec3( 1.0, -uv.y, -uv.x)); // +X
        case 1: return normalize(vec3(-1.0, -uv.y,  uv.x)); // -X
        case 2: return normalize(vec3( uv.x,  1.0,  uv.y)); // +Y
        case 3: return normalize(vec3( uv.x, -1.0, -uv.y)); // -Y
        case 4: return normalize(vec3( uv.x, -uv.y,  1.0)); // +Z
        case 5: return normalize(vec3(-uv.x, -uv.y, -1.0)); // -Z
    }
}

void main()
{
    uint face = gl_GlobalInvocationID.z; //Cube face
    vec2 uv = (gl_GlobalInvocationID.xy + 0.5) / imageSize(irradianceImage).xy;

    vec3 normal = GetNormal(face, uv);

    vec3 irradiance = vec3(0.0);

    vec3 up = vec3(0.0, 1.0, 0.0);
    vec3 right = normalize(cross(up, normal));
    up = normalize(cross(normal, right));

    float sampleDelta = 0.025;
    float nrSamples = 0.0;

    for (float phi = 0.0; phi < 2.0 * PI; phi += sampleDelta)
    {
        for (float theta = 0.0; theta < 0.5 * PI; theta += sampleDelta)
        {
            vec3 tangentSample = vec3(sin(theta) * cos(phi),  sin(theta) * sin(phi), cos(theta));

            vec3 sampleVec = tangentSample.x * right + tangentSample.y * up + tangentSample.z * normal; 

            irradiance += texture(environmentMap, SampleSphericalMap(normalize(sampleVec))).rgb; 
            nrSamples++;
        }
    }
    imageStore(irradianceImage, ivec3(gl_GlobalInvocationID.xy, face), vec4(irradiance, 1.0));
}