#version 450
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
layout(set = 0, binding = 0) uniform sampler2D environmentMap;
layout(rgba32f,set = 0, binding = 1) uniform imageCube irradianceImage;

#include "math.glsl"

void main()
{
    uint face = gl_GlobalInvocationID.z; //Cube face
    vec2 uv = (gl_GlobalInvocationID.xy + 0.5) / imageSize(irradianceImage).xy;

    vec3 normal = GetNormal(face, uv);

    vec3 irradiance = vec3(0.0);

    vec3 up = vec3(0.0, 1.0, 0.0);
    vec3 right = normalize(cross(up, normal));
    up = normalize(cross(normal, right));

    float sampleDelta = 0.01;
    float nrSamples = 0.0;

    // vec3 sampleVec = normal;

    // irradiance = texture(environmentMap, SampleSphericalMap(normalize(sampleVec))).rgb; 

    // imageStore(irradianceImage, ivec3(gl_GlobalInvocationID.xy, face), vec4(irradiance, 1.0));

    for (float phi = 0.0; phi < 2.0 * PI; phi += sampleDelta)
    {
        for (float theta = 0.0; theta < 0.5 * PI; theta += sampleDelta)
        {
            vec3 tangentSample = vec3(sin(theta) * cos(phi),  sin(theta) * sin(phi), cos(theta));

            vec3 sampleVec = tangentSample.x * right + tangentSample.y * up + tangentSample.z * normal; 

            irradiance += texture(environmentMap, SampleSphericalMap(normalize(sampleVec))).rgb * cos(theta) * sin(theta); 
            nrSamples++;
        }
    }

    irradiance = PI * irradiance * (1.0 / float(nrSamples));
    imageStore(irradianceImage, ivec3(gl_GlobalInvocationID.xy, face), vec4(irradiance, 1.0));
}