#version 460

layout (local_size_x = 16, local_size_y = 16) in;

layout(rgba16f,set = 0, binding = 0) uniform image2D image;
layout(set = 0, binding = 1) uniform sampler2D cloudTex;

//push constants block
layout( push_constant ) uniform constants
{
 vec4 data1;
 vec4 data2;
 vec4 data3;
 vec4 data4;
 vec4 cameraPos;
 ivec4 screenDimensions;
 mat4 view;
 mat4 invProj;
} PushConstants;

const float PI = 3.1415926535;

float noise(vec2 uv)
{
	uv.x += PushConstants.data4.z;
	uv.y += PushConstants.data4.z;
	return texture(cloudTex, uv).x;
}


void main() 
{
	ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);

	ivec2 size = PushConstants.screenDimensions.xy;
	
	vec2 uv = vec2(texelCoord) / vec2(size);
	uv = uv * 2.0 - 1.0;
	uv.x *= float(size.x) / float(size.y);
	
	//Clouds
	const float CLOUD_HEIGHT = 100.0;
	vec3 planeNormal = vec3(0.0, 1.0, 0.0);
	vec3 planePoint = vec3(0.0, CLOUD_HEIGHT, 0.0);
	
	vec2 ndc = (vec2(texelCoord) + 0.5) / vec2(size) * 2.0 - 1.0;
	ndc.y = -ndc.y;
	
	vec4 clip = vec4(ndc, 1.0, 1.0);
	vec4 viewRay = PushConstants.invProj * clip;
	vec3 rayView = normalize(viewRay.xyz / viewRay.w);
	
	vec3 rd = normalize(mat3(PushConstants.view) * rayView);
	vec3 ro = PushConstants.cameraPos.xyz;
	
	float denom = dot(rd, planeNormal);
	
	vec4 col = PushConstants.data1;
	
	if (denom > 0.01)
	{
		float t = dot(planePoint - ro, planeNormal) / denom;
		
		if (t > 0.0)
		{
			vec3 hitPos = ro + rd * t;
			
			vec2 skyUV = hitPos.xz * 0.001;
			float clouds = noise(skyUV);
			
			col = col + clouds;
		}
	}
	
	//Sun
	
	vec3 lDirection = normalize(vec3(-.8, .8, -.3));
	float sunDot = clamp(dot(rd, lDirection), 0.0, 1.0);
	
	vec3 sun = 0.25 * vec3(1.0, 0.8, 0.4) * pow(sunDot, 5.0);
    	sun += 0.25 * vec3(1.0,0.8,0.6) * pow( sunDot,64.0 );
    	sun += 0.2 * vec3(1.0,0.8,0.6) * pow( sunDot,512.0 );

	col += vec4(sun, 0.0f);
	
	imageStore(image, texelCoord, col);
}

